import {Injectable} from '@angular/core';
import {Observable, of} from "rxjs";
import {GPuntajes, Puntaje} from "./models/puntajes";

@Injectable({
  providedIn: 'root'
})
export class PuntajesService {

  constructor() {
  }

  private toPuntajes(gpuntajes: GPuntajes): Puntaje[] {
    return gpuntajes.values.slice(1).map(v => new Puntaje(v))
  }

  getPuntajes(): Observable<Puntaje[]> {
    return of(this.toPuntajes({
      "values": [
        [
          "PAIS",
          "ALAS",
          "FUSELAJE",
          "RUEDAS",
          "COLA",
          "NAFTA"
        ],
        [
          "ALEMANIA",
          "1",
          "1",
          "1",
          "1",
          "90"
        ],
        [
          "ARABIA SAUDITA",
          "2",
          "1",
          "2",
          "2",
          "80"
        ],
        [
          "ARGENTINA",
          "3",
          "1",
          "3",
          "3",
          "70"
        ],
        [
          "BELGICA",
          "1",
          "1",
          "1",
          "1",
          "60"
        ],
        [
          "BRASIL",
          "2",
          "1",
          "2",
          "2",
          "50"
        ],
        [
          "CAMERUN",
          "3",
          "1",
          "3",
          "3",
          "40"
        ],
        [
          "CANADA",
          "1",
          "1",
          "1",
          "1",
          "30"
        ],
        [
          "COLOMBIA",
          "2",
          "1",
          "2",
          "2",
          "20"
        ],
        [
          "COREA",
          "3",
          "1",
          "3",
          "3",
          "10"
        ],
        [
          "CROACIA",
          "1",
          "1",
          "1",
          "1",
          "0"
        ],
        [
          "DINAMARCA",
          "2",
          "1",
          "2",
          "2",
          "90"
        ],
        [
          "ECUADOR",
          "3",
          "1",
          "3",
          "3",
          "80"
        ],
        [
          "EGIPTO",
          "1",
          "1",
          "1",
          "1",
          "70"
        ],
        [
          "ESPAÑA",
          "2",
          "1",
          "2",
          "2",
          "60"
        ],
        [
          "ESTADOS UNIDOS",
          "3",
          "1",
          "3",
          "3",
          "50"
        ],
        [
          "FRANCIA",
          "1",
          "1",
          "1",
          "1",
          "40"
        ],
        [
          "GHANA",
          "2",
          "1",
          "2",
          "2",
          "30"
        ],
        [
          "HOLANDA",
          "3",
          "1",
          "3",
          "3",
          "20"
        ],
        [
          "INGLATERRA",
          "1",
          "1",
          "1",
          "1",
          "10"
        ],
        [
          "IRAN",
          "2",
          "1",
          "2",
          "2",
          "0"
        ],
        [
          "JAPON",
          "3",
          "1",
          "3",
          "3",
          "90"
        ],
        [
          "MEXICO",
          "1",
          "1",
          "1",
          "1",
          "80"
        ],
        [
          "PERU",
          "2",
          "1",
          "2",
          "2",
          "70"
        ],
        [
          "POLONIA",
          "3",
          "1",
          "3",
          "3",
          "60"
        ],
        [
          "PORTUGAL",
          "1",
          "1",
          "1",
          "1",
          "50"
        ],
        [
          "QATAR",
          "2",
          "1",
          "2",
          "2",
          "40"
        ],
        [
          "RUSIA",
          "3",
          "1",
          "3",
          "3",
          "30"
        ],
        [
          "SENEGAL",
          "1",
          "1",
          "1",
          "1",
          "20"
        ],
        [
          "SERBIA",
          "2",
          "1",
          "2",
          "2",
          "10"
        ],
        [
          "SUIZA",
          "3",
          "1",
          "3",
          "3",
          "67"
        ],
        [
          "TUNEZ",
          "2",
          "1",
          "2",
          "2",
          "43"
        ],
        [
          "URUGUAY",
          "1",
          "1",
          "1",
          "1",
          "32"
        ]
      ]
    }));
  }
}
