import {Injectable} from '@angular/core';
import {Observable, of} from "rxjs";
import {Puntaje} from "./models/puntajes";
import {GSheet} from "./models/gsheet";

@Injectable({
  providedIn: 'root'
})
export class PuntajesService {

  constructor() {
  }

  private toPuntajes(gsheet: GSheet): Puntaje[] {
    return gsheet.values.slice(1).map(v => new Puntaje(v))
  }

  getPuntajes(): Observable<Puntaje[]> {
    return of(this.toPuntajes({
      "values": [
        [
          "PAIS",
          "ALAS",
          "FUSELAJE",
          "RUEDAS",
          "COLA",
          "NAFTA",
          "MOTOR",
          "PASAPORTE"
        ],
        [
          "ALEMANIA",
          "1",
          "0",
          "1",
          "1",
          "90",
          "0",
          "0"
        ],
        [
          "ARABIA SAUDITA",
          "2",
          "1",
          "2",
          "2",
          "80",
          "1",
          "1"
        ],
        [
          "ARGENTINA",
          "3",
          "0",
          "3",
          "3",
          "70",
          "0",
          "0"
        ],
        [
          "BELGICA",
          "1",
          "1",
          "1",
          "1",
          "60",
          "1",
          "1"
        ],
        [
          "BRASIL",
          "2",
          "0",
          "2",
          "2",
          "50",
          "0",
          "0"
        ],
        [
          "CAMERUN",
          "3",
          "1",
          "3",
          "3",
          "40",
          "1",
          "1"
        ],
        [
          "CANADA",
          "1",
          "0",
          "1",
          "1",
          "30",
          "0",
          "0"
        ],
        [
          "COLOMBIA",
          "2",
          "1",
          "2",
          "2",
          "20",
          "1",
          "1"
        ],
        [
          "COREA",
          "3",
          "0",
          "3",
          "3",
          "10",
          "0",
          "0"
        ],
        [
          "CROACIA",
          "1",
          "1",
          "1",
          "1",
          "0",
          "1",
          "1"
        ],
        [
          "DINAMARCA",
          "2",
          "0",
          "2",
          "2",
          "90",
          "0",
          "0"
        ],
        [
          "ECUADOR",
          "3",
          "1",
          "3",
          "3",
          "80",
          "1",
          "1"
        ],
        [
          "EGIPTO",
          "1",
          "0",
          "1",
          "1",
          "70",
          "0",
          "0"
        ],
        [
          "ESPAÑA",
          "2",
          "1",
          "2",
          "2",
          "60",
          "1",
          "1"
        ],
        [
          "ESTADOS UNIDOS",
          "3",
          "0",
          "3",
          "3",
          "50",
          "0",
          "0"
        ],
        [
          "FRANCIA",
          "1",
          "1",
          "1",
          "1",
          "40",
          "1",
          "1"
        ],
        [
          "GHANA",
          "2",
          "0",
          "2",
          "2",
          "30",
          "0",
          "0"
        ],
        [
          "HOLANDA",
          "3",
          "1",
          "3",
          "3",
          "20",
          "1",
          "1"
        ],
        [
          "INGLATERRA",
          "1",
          "0",
          "1",
          "1",
          "10",
          "0",
          "0"
        ],
        [
          "IRAN",
          "2",
          "1",
          "2",
          "2",
          "0",
          "1",
          "1"
        ],
        [
          "JAPON",
          "3",
          "0",
          "3",
          "3",
          "90",
          "0",
          "0"
        ],
        [
          "MEXICO",
          "1",
          "1",
          "1",
          "1",
          "80",
          "1",
          "1"
        ],
        [
          "PERU",
          "2",
          "0",
          "2",
          "2",
          "70",
          "0",
          "0"
        ],
        [
          "POLONIA",
          "3",
          "1",
          "3",
          "3",
          "60",
          "1",
          "1"
        ],
        [
          "PORTUGAL",
          "1",
          "0",
          "1",
          "1",
          "50",
          "0",
          "0"
        ],
        [
          "QATAR",
          "2",
          "1",
          "2",
          "2",
          "40",
          "1",
          "1"
        ],
        [
          "RUSIA",
          "3",
          "0",
          "3",
          "3",
          "30",
          "0",
          "0"
        ],
        [
          "SENEGAL",
          "1",
          "1",
          "1",
          "1",
          "20",
          "1",
          "1"
        ],
        [
          "SERBIA",
          "2",
          "0",
          "2",
          "2",
          "10",
          "0",
          "0"
        ],
        [
          "SUIZA",
          "3",
          "1",
          "3",
          "3",
          "0",
          "1",
          "1"
        ],
        [
          "TUNEZ",
          "2",
          "0",
          "2",
          "2",
          "43",
          "0",
          "0"
        ],
        [
          "URUGUAY",
          "1",
          "1",
          "1",
          "1",
          "32",
          "1",
          "1"
        ]
      ]
    }));
  }
}
